name: Deploy to Calculator GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install PKCalc dependencies
        run: cd PKCalc && npm install 
      - name: Install Showdown Calc Dependencies
        run: cd PKCalc/calc && npm install
      - name: Build
        run: |
          cd PKCalc && node build
          rm -rf ../dist
          cp -r dist ../dist